# Generated by Django 2.1.5 on 2019-01-08 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('identification', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{,12}$', 'Số cmnd không hợp lệ')])),
                ('email', models.EmailField(max_length=75)),
                ('phone_number', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Số điện thoại không đúng định dạng', regex='^\\d{6,15}$')])),
                ('status', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
